### ISSUE TITLE
RC Quad-D Dokumentation Version 0.2, 15.02.2021

### ISSUE THREAD

**Issue by Hainer2001** [wimalopaan/Electronics#1]
Eine Übersicht der Anschlüsse und LEDs auf der Platine scheint hilfreich.
Die Stecker für IBUS/SBUS und Telemtrie sind Identisch, eine Beschriftung auf der Platine währe hilfreich um Sie richtig zuzuordnen.
Die Belegung der Steckerleiste für die Endschalter ist nicht eindeutig bzw nicht beschriftet.

**Comment by wimalopaan** [comment]
Doku verbessert
