### ISSUE TITLE
Fehler in der Konfiguration

### ISSUE THREAD

**Issue by Hainer2001** [wimalopaan/Electronics#4]
Nach der Konfiguration treten Fehler auf.
So wird nach der Konfiguration von M1 und M3 die Funtionalität nicht ausgeführt.
Die Konfiguration wurde wie folgt durchgeführt .

    Der Curser wurde in die Erste Zeile Paramter "RES" ,dann mit S1 den Wert 1 eingestellt dannach "Enter" gedrückt.
    Der Curser eine Position nach rechts gestellt "PWM", dann mit S1 einen Wert von 1bis15 eingestllt dannach "Enter" gedrückt.
    Dabei wird der angeschlossene Motor schon mit Spannung versorgt läuft aber nicht an.
    Den Cursor weiter nach rechts gestellt "B1i" ,dann mit S1 einen Wert zwischen 1 und 15 eingestellt "Enter" gedrückt.
    Der angeschlossene Motor läuft für ca1 Sec an, die Geschwindigkeit variier ja nach gewähltem Wert.
    Den Cursor nach rechts auf "B1d" gestellt,dann mit S1 einen Wert zwischen 1bis 15 eingestellt und "Enter" gedrückt.
    Den Cursor nach recht auf "B2i" gestellt,dann mit S1 einen Wert zwischen 1 und 15 eingestellt "Enter" gedrückt.
    Der angeschlossene Motor läuft für ca.1Sek an, die Geschwindigkeit variier ja nach gewähltem Wert.
    Den Cursor nach rechts auf "B2d" gestellt,dann mit S1 einen Wert zwischen 1bis 15 eingestellt und "Enter" gedrückt.

Das Script mit Exit verlassen dann im Telemetrie menu das konfigurationsscript entfernt und das Bedienscript eingefügt.
(FrSky X9e)

Nach dem Einschalten des Empfängers blinkt zunächst die "BUS LED" , eine weitere LED vor dem Klemmenblock leuchtet zunächst und erlischt dann.
Nun wird die Betriebsspannung angelegt (6,3V aus einem Stepdown Regler).Mit dem Schalter SB wird der Motor angesteuert, in die Richtung B läuft der Motor entsprechend der Parametrierung an und ist durch abbremsen auch auszuschalten was durch leuchten der LED vor dem Klemmenblock angezeigt wird. Bei Ansteuern in die Gegenrichtung passier nichts, der Motor läuft nicht an es liegen 0V an den Motorklemmen. Keine LED leuchtet bis auf das Blinken der "BUS LED".

Dieses Verhalten ist unabhängig von allen eingestellten Parametern für den Motor 1 und 3 .
Die Motoren 2 und 4 funktionieren wie erwartet entsprend Ihre Parametrierung.

**Comment by wimalopaan** [comment]
should be fixed now
