### ISSUE TITLE
Dokumentation RC Quad-D Version 0.2, 15.02.2021 Fehler in Kapitel 11

### ISSUE THREAD

**Issue by Hainer2001** [wimalopaan/Electronics#5]
11.2.1. Abschaltung durch Endlagenkontakte

Die einfachste Form der Endlagenabschaltung eines jeden Kanals ist diejenige, die je Kanala zwei
Endlagenkontakte verwenden. Wird einer der beiden Kontakte geschlossen, so wird der Motor
unmittelbar abgeschaltet. Ein erneutes Anlaufen ist dann nur in die Gegenrichtung möglich. Bei
Kontakte werden parallel angeschlossen.

> 
> [end1] | end1.jpg
> 
**_Hier hat das Einbinden eines Bildes nicht geklappt_**

Abbildung 20. Anschluss der Endlagenschalter

**Comment by wimalopaan** [comment]
fixed
