### ISSUE TITLE
RC-Quad-D: Neuer Absschalt Methode

### ISSUE THREAD

**Issue by Hainer2001** [wimalopaan/Electronics#6]
Bei manchen Antrieben ist nur an einer Seite ein Mechanischer Anschlag möglich.
Hier währe es wünschenswert eine Lösung für das Abschalten auf der gegenüberliegende Seite zu haben.

Die überlegung ist, den Antrieb in den Mechanischen Anschlag zu fahren um diese Position als Referenz zu nutzen. Nun könnte ein Zähler oder etwas ähnliches den Betrieb in die "offene Seite" überwachen . Wird der Wert diese Zähler überschritte so soll der Antrieb ausgeschaltet werden und nur noch in die Gegenrichtung zu starten sein. Als Parameter währe die gewünschte Strecke in der Einheit des Zählers zu übergeben.

**Comment by wimalopaan** [comment]
Das mag bei kompletten Vor-/Rück-Abläufen funktionieren, jedoch erscheint es mit zu ungenau, wenn zwischendurch mehrmals angehalten und umgekehrt wird. Um auch noch Hall-Geber für die Umdrehungszählung anzuschließen, fehlen im Moment die Anschlüsse.

**Comment by Hainer2001** [comment]
Wäre zu klären wieviel "ungenau" bedeutet. Ungenau abschalten kann besser sein als garnicht abschalten. Eine Toleranz von 1-4mm ist z.Z akzeptabel.Für meine Anwendung gibt es keinen Raum für Hallsensoren.
