### ISSUE TITLE
INCREM mit Deadband

### ISSUE THREAD

**Issue by THKLGruen** [wimalopaan/Electronics#7]
Da die Chinesischen präzisions Potetiometer nicht immer im Mittelpunkt zentrieren, läuft der Ausgabe Wert oft langsam weiter.
Um das zu verhintern hab ich mir erlaubt eine Deadband funktion einzubauen. Mit der Variablen deadband kann der Bereich um den 0-punkt eingestellt werden.

Ich steck das Script mal hier rein.

-- WM OTXE - OpenTX Extensions 
-- Copyright (C) 2020 Wilhelm Meier <wilhelm.wm.meier@googlemail.com>
--
-- This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License. 
-- To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/4.0/ 
-- or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.

local input = {
   {"Input", SOURCE},
   {"Reset", SOURCE},
   {"Deadb", VALUE, 0, 100, 2},
   {"Scale", VALUE, 0, 100, 10}
};

local output = { 
"Incremental"};

local value = 0;

local function run(s, r, b, d)

   if (r > 0)  then
      value = 0;
   else
     if (s < -b*10) or (s > b*10)then 
       local i = (s * d) / 10240;
       value = value + i;
       value = math.min(value, 1024);
       value = math.max(value, -1024);
	  end
   end
   return value;
end

return {input=input, output=output, run=run}

**Comment by wimalopaan** [comment]
Closed via https://github.com/wimalopaan/EdgeLua/commit/c994fac343ef4f8d4cb8e68706c1d331182f9617
